jobs:
  - template: default.yml@templates
    parameters:
      minrust: 1.33.0

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      endpoint: hunter04d
