[package]
name = "rusty_yard"
version = "0.3.1"
authors = ["hunter04d <hunter04d@gmail.com>"]
edition = "2018"

[profile.release]
lto = true

[dependencies]
lazy_static = "1.4"
thiserror = "1.0"

[dev-dependencies]
proptest = "0.10"
criterion = "0.3"

[[bench]]
name = "full"
harness = false
